tMaps = {
	{"Vâ L©m Minh",425,1756,3200},
	{"BiÖn Kinh",200,1390,2823},
	{"§¹i ViÖn",425,1756,3200},
	{"Néi ViÖn",425,1756,3200},
	{"Liªn Hoµn sµo",425,1756,3200},
	{"KiÕm trñng",425,1756,3200},
}


tTieuHao = {
	{"§Êu hån", {2,1,1157},10},
	{"B¸nh ng«", {1,1,1},999},
	{"Xuyªn cèt ch©m", {2,11,2},2000},
	{"TrÊn ma ch©m", {2,11,5},2000},
	{"ThÇn hµnh b¶o ®iÓn", {0,200,40},1},
	{"Gi¸m ®Þnh phï cÊp 7", {2,5,7},10},
	-- {"TiÓu bao gi¸m ®Þnh phï cÊp 7",{2,1,1057},1},
	{"Thiªn c¬ ®å",{2,1,1179},1},
	{"ThÇn Hµnh Phï", {2,0,143},999},
	{"Th«ng Thiªn LÖnh",{2,1,30409},1},
	{"Th­ëng thiÖn lÖnh", {2,1,30258},1},
	{"Ph¹t ¸c lÖnh", {2,1,30259},1},
	{"Tester", {2,1,29007},1},
	{"Checker", {2,1,29008},1},
	{"Kho ®å di ®éng", {2,1,29001},1},
	{"Tµng KiÕm LÖnh", {2,1,30115},1},
	{"Vâ L©m triÖu tËp lÖnh", {2,1,30760},1},
	{"Thiªn lý truyÒn ©m phï", {2,0,3508},99},
	{"Hoµng Kim LÖnh", {2,1,30284},99},
	{"Ch×a khãa vµng", {2,0,1050},1},
	{"BiÖn Kinh håi phï", {1,5,1},10},
	{"§u«i thá", {2,1,2},10},
	{"B¹ch c©u hoµn", {2,1,270},10},
}

tDecorators = {
	{"STR_G_MAN_STD"},
	{"STR_G_MAN_STRONG"},
	{"STR_G_WOMAN_SEXY"},
	{"STR_G_WOMAN_AMORETTO"},
	{"NguyÖt L·o"},
	{"T­ M· Quang"},
	{"Cô giµ"},
	{"Quan viªn"},
	{"ThÈm Qu¸t"},
	{"Diªm La"},
	{"H¾c V« Th­êng"},
	{"B¹ch V« Th­êng"},
	{"Quû Sai"},
	{"TriÖu C¸t"},
	{"Con b¹c"},
	{"Thanh niªn nam"},
	{"Lý S­ S­"},
	{"Tè Hoµn Ch©n"},
	{"N÷ thiÕu niªn1"},
	{"N÷ thiÕu niªn2"},
	{"N÷ thiÕu niªn3"},
	{"M¹nh Bµ"},
	{"Bµ l·o1"},
	{"Bµ l·o2"},
	{"Bµ l·o3"},
	{"Phô n÷1"},
	{"Phô n÷2"},
	{"Tó bµ"},
	{"§ång tö1"},
	{"§ång tö2"},
	{"§ång tö 3"},
	{"§ång n÷1"},
	{"§ång n÷2"},
	{"§ång n÷3"},
	{"§ång Qu¸n"},
	{"Miªu téc thiÕu n÷1"},
	{"Miªu téc tiÓu n÷2"},
	{"¡n mµy"},
	{"Du Ph­¬ng T­íng SÜ"},
	{"ThiÕu niªn nam1"},
	{"ThiÕu niªn nam2"},
	{"ThiÕu niªn3"},
	{"Th«n phô1"},
	{"Th«n phô2"},
	{"Th«n phô 3"},
	{"Qu¶n gia"},
	{"Ngù Trï"},
	{"V©n Du §¹o Nh©n"},
	{"ThÇy luyÖn thó"},
	{"ThÇy nghi thøc"},
	{"Thî c¹o"},
	{"Vâ L©m truyÒn nh©n"},
	{"Dßng th«ng b¸o"},
	{"L·o phó hé"},
	{"Quan sø-trung niªn1"},
	{"Quan sø2"},
	{"Quan sø3"},
	{"Vâ L©m Minh Chñ1"},
	{"Vâ L©m Minh Chñ2"},
	{"Th­ sinh"},
	{"Xa Th¸i Qu©n"},
	{"Phu nh©n (cao)"},
	{"Phu nh©n-phæ th«ng"},
	{"§¹i tiÓu th­ tËp vâ"},
	{"HiÖp n÷"},
	{"L·o n«ng d©n"},
	{"ThiÕu niªn trong th«n"},
	{"Bµ l·o n«ng d©n"},
	{"D©n n÷"},
	{"B¸n s¸ch"},
	{"G¸nh hµng"},
	{"B¸n hµng"},
	{"KÑo hå l«"},
	{"Bµ chñ"},
	{"Ng­ d©n"},
	{"Tèng T­íng Qu©n"},
	{"Nam nh©n T©y Nam"},
	{"Phô n÷ T©y Nam"},
	{"Nam nh©n T©y B¾c"},
	{"Phô n÷ T©y B¾c"},
	{"TruyÒn gi¸o sÜ"},
	{"Phu nh©n T©y D­¬ng"},
	{"Th­¬ng nh©n Ba T­"},
	{"Vò n÷ Ba T­"},
	{"C©y Gi¸ng Sinh (lín)"},
	{"c©y Gi¸ng Sinh (trung)"},
	{"C©y Gi¸ng Sinh (nhá)"},
	{"Hoa ®¨ng1"},
	{"Hoa ®¨ng2"},
	{"Hoa ®¨ng3"},
	{"Hép quµ lín1"},
	{"Hép quµ trung1"},
	{"Hép quµ nhá1"},
	{"Hép quµ lín2"},
	{"Hép quµ trung2"},
	{"Hép quµ nhá2"},
	{"Hép quµ lín3"},
	{"Hép quµ trung3"},
	{"Hép quµ nhá3"},
	{"Hép quµ lín4"},
	{"Hép quµ trung4"},
	{"Hép quµ nhá4"},
	{"C©y gi¸ng sinh"},
	{"C©y gi¸ng sinh ®Æc biÖt"},
	{"Hoa hång ®á"},
	{"Hoa hång vµng"},
	{"Hoa hång tr¾ng"},
	{"MÇm hoa hång"},
	{"MÇm Hoa hång"},
	{" nh¸nh hoa hång"},
	{"c©y §a MËt Hoa Qu¶ nhá"},
	{"c©y §a MËt Hoa Qu¶ trung"},
	{"c©y §a MËt Hoa Qu¶ lín"},
	{"B¾c Lôc L©m lÖnh"},
	{"Trôc ¶nh Th­¬ng"},
	{"TuyÖt T×nh Th¹ch"},
	{"LÖnh bµi tæng qu¶n ngo¹i viÖn"},
	{"LÖnh bµi tæng qu¶n néi viÖn"},
	{"ViÖt N÷ kiÕm"},
	{"Trang chñ kim Ên"},
	{"Tr­ëng L·o ChØ Hoµn"},
	{"Ng­u Lang"},
	{"Chøc N÷"},
	{"Chim kh¸ch"},
	{"KiÖu"},
	{"M©m cç"},
	{"Bµ mai"},
	{"Hû N­¬ng"},
	{"Th­¬ng nh©n"},
	{"Ng­êi ®¸nh trèng"},
	{"Ng­êi thæi kÌn"},
	{"Chim kh¸ch ph¶i"},
	{"Chim kh¸ch tr¸i"},
	{"Trïng D­¬ng hoa 1"},
	{"Trïng D­¬ng hoa 2"},
	{"Trïng D­¬ng hoa 3"},
	{"C©y Gi¸ng sinh 1a"},
	{"C©y Gi¸ng sinh 1b"},
	{"C©y Gi¸ng sinh 1c"},
	{"C©y Gi¸ng sinh 1d"},
	{"C©y Gi¸ng sinh 2a"},
	{"C©y Gi¸ng sinh 2b"},
	{"C©y Gi¸ng sinh 2c"},
	{"C©y Gi¸ng sinh 2d"},
	{"C©y Gi¸ng sinh 3a"},
	{"C©y Gi¸ng sinh 3b"},
	{"C©y Gi¸ng sinh 3c"},
	{"C©y Gi¸ng sinh 3d"},
	{"C©y Gi¸ng sinh 4a"},
	{"C©y Gi¸ng sinh 4b"},
	{"C©y Gi¸ng sinh 4c"},
	{"C©y Gi¸ng sinh 4d"},
	{"Tói cao thñ"},
	{"Thè TiÓu Nha"},
	{"TiÓu B¹ch tr­ (bè)"},
	{"TiÓu B¹ch tr­ (mÑ)"},
	{"TiÓu H¾c tr­ (bè)"},
	{"TiÓu H¾c tr­ (mÑ)"},
	{"TiÓu Kim tr­ (bè)"},
	{"TiÓu Kim tr­ (mÑ)"},
	{"Hoa S¬n r­¬ng"},
	{"Brazil"},
	{"Argentina"},
	{"Anh"},
	{"ý"},
	{"Ph¸p"},
	{"Hµ Lan"},
	{"T©y Ban Nha"},
	{"Bå §µo Nha"},
	{"§øc 1"},
	{"Brazil 1"},
	{"Argentina 1"},
	{"Anh 1"},
	{"ý 1"},
	{"Ph¸p 1"},
	{"Hµ Lan 1"},
	{"T©y Ban Nha 1"},
	{"Bå §µo Nha 1"},
	{"Zakumi"},
	{"WorldCup Cart"},
	{"TiÓu Hoµng Kª"},
	{"TiÓu B¹ch Nha"},
	{"DiÒu xanh"},
	{"DiÒu ®á"},
	{"DiÒu vµng"},
	{"DiÒu lôc"},
	{"DiÒu b¶y mµu"},
	{"Löa tr¹i"},
	{"BOSS tuyÕt yªu ®èi tho¹i"},
	{"BOSS tuyÕt yªu chiÕn ®Êu"},
	{"TuyÕt qu¸i 1"},
	{"TuyÕt qu¸i 3"},
	{"C©y Tø Linh 1"},
	{"C©y Tø Linh 2_1"},
	{"C©y Tø Linh 2_2"},
	{"C©y Tø Linh 3_1"},
	{"C©y Tø Linh 3_2"},
	{"C©y Tø Linh 4"},
	{"C©y hoa qu¶"},
	{"C©y B¹ch Kim"},
	{"Löa tr¹i"},
	{"HÇu T«n"},
	{"Ruéng Hoang"},
	{"Ruéng võa n¶y mÇm "},
	{"Ruéng ®ang ph¸t triÓn "},
	{"Ruéng ®· chin mïi "},
	{"Xe vËn l­¬ng "},
	{"Tè tiªn Thu Nh­îc Thñy"},
	{"§ång ®¹o vâ l©m 2"},
	{"Sµi Phong Nhi"},
}